name: Validation Pipeline

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: "Target branch to validate"
        required: true
        type: string
        default: master
      path:
        description: "Path to the manifest"
        required: true
        type: string

jobs:
  validate:
    name: Validate manifests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          repository: Dragon1573/winget-pkgs
          ref: "${{ inputs.branch }}"
          sparse-checkout: "${{ inputs.path }}"
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: Enable features
        # Unlock 2 important limitations for further tests.
        run: |-
          winget config --enable LocalManifestFiles
          winget settings --enable LocalArchiveMalwareScanOverride
      - name: Install package
        # We have to silently install everything on CI/CD, disable Microsoft SmartScreen,
        # and silently accept all agreements to prevent installation fail.
        run: |-
          winget install --manifest "${{ inputs.path }}" `
            --silent --ignore-local-archive-malware-scan --accept-package-agreements --accept-source-agreements
