name: Validation Pipeline

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Target repository to checkout"
        required: true
        type: string
        default: "${{ github.repository_owner }}/winget-pkgs"
      branch:
        description: "Target branch to validate"
        required: true
        type: string
      path:
        description: "Path to the manifest"
        required: true
        type: string

jobs:
  validate:
    name: Validate manifests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          repository: "${{ inputs.repository }}"
          ref: "${{ inputs.branch }}"
          sparse-checkout: "${{ inputs.path }}"
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: Enable features
        run: |-
          # Unlock 2 important limitations for further tests.
          winget config --enable LocalManifestFiles
      - name: Install package
        run: |-
          # We have to silently install everything on CI/CD, disable Microsoft SmartScreen,
          # and silently accept all agreements to prevent installation fail.
          winget install --manifest "${{ inputs.path }}" `
            --silent --accept-package-agreements --accept-source-agreements
